#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: AuthenticationService
#          uri: lb://AUTHENTICATIONSERVICE
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - AuthenticationFilter
